version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
