version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data:
