# Generated by Django 5.1.5 on 2025-02-25 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
