# Generated by Django 5.1.5 on 2025-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
