# Generated by Django 5.1.5 on 2025-03-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage_options',
            field=models.JSONField(default=dict),
        ),
    ]
