# Generated by Django 5.1.5 on 2025-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
