# Generated by Django 5.1.5 on 2025-03-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_showroom_delete_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowRoom',
            new_name='Store',
        ),
    ]
