# Generated by Django 5.1.6 on 2025-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_order_id_payment_momo_order_id_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='momo_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
