# Generated by Django 5.1.6 on 2025-07-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_payment_momo_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('cod', 'tiền mặt')], default='cod', max_length=50),
        ),
    ]
